# Generated by Django 4.1 on 2022-08-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.basemodel')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Gain',
                'ordering': ['-created_at'],
            },
            bases=('store.basemodel',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.basemodel')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('quantity', models.IntegerField(blank=True, verbose_name='quantity')),
                ('child_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.listitem', verbose_name='child list')),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='store.listitem', verbose_name='origin list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Item',
                'ordering': ['-created_at'],
            },
            bases=('store.basemodel',),
        ),
    ]
