# Generated by Django 4.1 on 2022-08-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'List Item'},
        ),
        migrations.AlterField(
            model_name='item',
            name='child_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.item', verbose_name='child item'),
        ),
    ]
